In [1]:
from pathlib import Path
import pandas as pd

# 1. Ruta relativa al archivo desde la raíz del proyecto
json_path = Path("fightmatrix/fightmatrix/spiders/dwcs.json")

# Cargar las stats de los peleadores directamente desde el archivo JSON
df_fighters = pd.read_json(json_path)

# 2. Definir o cargar la lista de matchups
matchups_json = [
    {"matchup": "Patrick Rivera vs Adam Darby"},
    {"matchup": "Brandon Holmes vs Modestino Rodrigues"},
    {"matchup": "Hunter Smith vs Adam Livingston"},
    {"matchup": "Liam McCracken vs Silvestre Sanchez"},
    {"matchup": "Gabriel Lourenco vs Charlie Cleveland"},
]
df_matchups = pd.DataFrame(matchups_json)

# 3. Separar el campo "matchup" en dos columnas de nombres
df_matchups[["fighter_1", "fighter_2"]] = df_matchups["matchup"].str.split(
    " vs ", expand=True
)

# 4. Cruzar la información del Peleador 1 y Peleador 2 lado a lado
df_merged = df_matchups.merge(
    df_fighters.add_suffix("_f1"),
    left_on="fighter_1",
    right_on="fighter_f1",
    how="left",
).merge(
    df_fighters.add_suffix("_f2"),
    left_on="fighter_2",
    right_on="fighter_f2",
    how="left",
)

# Mostrar el resultado final
df_merged

,matchup,fighter_1,fighter_2,fighter_f1,birthd_f1,prorecord_f1,ufcdebut_f1,ufcrecord_f1,oct_time_f1,longest_ws_f1,...,birthd_f2,prorecord_f2,ufcdebut_f2,ufcrecord_f2,oct_time_f2,longest_ws_f2,last_ufc_fight_f2,last_5_f2,association_f2,pro_d_date_f2
0,Patrick Rivera vs Adam Darby,Patrick Rivera,Adam Darby,Patrick Rivera,Maryland,13-4-0,NaN,NaN,NaT,NaN,...,1998-11-13,7-1-0,NaN,NaN,NaT,NaN,NaN,"[W, W, W, W, W]",Team Ryano,2022-06-25
1,Brandon Holmes vs Modestino Rodrigues,Brandon Holmes,Modestino Rodrigues,Brandon Holmes,Texas,6-1-0,NaN,NaN,NaT,NaN,...,NaN,7-1-0,NaN,NaN,NaT,NaN,NaN,"[L, W, W, W, W]",Revira Black Team,2021-12-22
2,Hunter Smith vs Adam Livingston,Hunter Smith,Adam Livingston,Hunter Smith,Louisiana,8-1-0,NaN,NaN,NaT,NaN,...,New York,7-1-0,NaN,NaN,NaT,NaN,NaN,"[W, W, W, L, W]",Long Island MMA,2022-09-10
3,Liam McCracken vs Silvestre Sanchez,Liam McCracken,Silvestre Sanchez,Liam McCracken,2001-07-09,8-1-0,NaN,NaN,NaT,NaN,...,2001-11-15,9-1-0,NaN,NaN,NaT,NaN,NaN,"[W, W, W, W, W]",UFC Performance Institute,2022-01-15
4,Gabriel Lourenco vs Charlie Cleveland,Gabriel Lourenco,Charlie Cleveland,Gabriel Lourenco,NaN,7-1-0,NaN,NaN,NaT,NaN,...,Ohio,6-1-0,NaN,NaN,NaT,NaN,NaN,"[L, W, W, W, W]",Demolition Fight Team,2025-02-01

In [4]:
def comparar_matchup(df_merged, index=0):
    # 1. Obtener la fila del matchup deseado
    row = df_merged.iloc[index]

    f1_name = row["fighter_1"]
    f2_name = row["fighter_2"]

    # 2. Identificar qué estadísticas existen (quitando los sufijos _f1 / _f2)
    stats = [
        col.replace("_f1", "")
        for col in df_merged.columns
        if col.endswith("_f1") and col != "fighter_f1"
    ]

    # 3. Armar un nuevo DataFrame comparativo
    datos_comparativos = []
    for stat in stats:
        datos_comparativos.append(
            {
                "Estadística": stat,
                f1_name: row[f"{stat}_f1"],
                f2_name: row[f"{stat}_f2"],
            }
        )

    df_comp = pd.DataFrame(datos_comparativos).set_index("Estadística")
    print(f"=== {row['matchup']} ===")
    return df_comp


# Ejemplo: Comparar la primera pelea (índice 0)
comparar_matchup(df_merged, index=3)

=== Liam McCracken vs Silvestre Sanchez ===

                              Liam McCracken          Silvestre Sanchez
Estadística
birthd                           2001-07-09                 2001-11-15
prorecord                              8-1-0                      9-1-0
ufcdebut                                 NaN                        NaN
ufcrecord                                NaN                        NaN
oct_time                                 NaT                        NaT
longest_ws                               NaN                        NaN
last_ufc_fight                           NaN                        NaN
last_5                       [W, W, W, W, W]            [W, W, W, W, W]
association     Aspire Combat Sports Academy  UFC Performance Institute
pro_d_date                        2022-01-22                 2022-01-15

In [5]:
def comparar_matchup(df_merged, index=0):
    # 1. Obtener la fila del matchup deseado
    row = df_merged.iloc[index]

    f1_name = row["fighter_1"]
    f2_name = row["fighter_2"]

    # 2. Identificar qué estadísticas existen (quitando los sufijos _f1 / _f2)
    stats = [
        col.replace("_f1", "")
        for col in df_merged.columns
        if col.endswith("_f1") and col != "fighter_f1"
    ]

    # 3. Armar un nuevo DataFrame comparativo
    datos_comparativos = []
    for stat in stats:
        datos_comparativos.append(
            {
                "Estadística": stat,
                f1_name: row[f"{stat}_f1"],
                f2_name: row[f"{stat}_f2"],
            }
        )

    df_comp = pd.DataFrame(datos_comparativos).set_index("Estadística")
    print(f"=== {row['matchup']} ===")
    return df_comp


# Ejemplo: Comparar la primera pelea (índice 0)
comparar_matchup(df_merged, index=1)

=== Brandon Holmes vs Modestino Rodrigues ===

                            Brandon Holmes Modestino Rodrigues
Estadística
birthd                               Texas                 NaN
prorecord                            6-1-0               7-1-0
ufcdebut                               NaN                 NaN
ufcrecord                              NaN                 NaN
oct_time                               NaT                 NaT
longest_ws                             NaN                 NaN
last_ufc_fight                         NaN                 NaN
last_5                     [W, W, W, L, W]     [L, W, W, W, W]
association     TNT Martial Arts & Fitness   Revira Black Team
pro_d_date                      2023-12-02          2021-12-22

In [6]:
def comparar_matchup(df_merged, index=0):
    # 1. Obtener la fila del matchup deseado
    row = df_merged.iloc[index]

    f1_name = row["fighter_1"]
    f2_name = row["fighter_2"]

    # 2. Identificar qué estadísticas existen (quitando los sufijos _f1 / _f2)
    stats = [
        col.replace("_f1", "")
        for col in df_merged.columns
        if col.endswith("_f1") and col != "fighter_f1"
    ]

    # 3. Armar un nuevo DataFrame comparativo
    datos_comparativos = []
    for stat in stats:
        datos_comparativos.append(
            {
                "Estadística": stat,
                f1_name: row[f"{stat}_f1"],
                f2_name: row[f"{stat}_f2"],
            }
        )

    df_comp = pd.DataFrame(datos_comparativos).set_index("Estadística")
    print(f"=== {row['matchup']} ===")
    return df_comp


# Ejemplo: Comparar la primera pelea (índice 0)
comparar_matchup(df_merged, index=0)

=== Patrick Rivera vs Adam Darby ===

                        Patrick Rivera       Adam Darby
Estadística
birthd                        Maryland      1998-11-13
prorecord                       13-4-0            7-1-0
ufcdebut                           NaN              NaN
ufcrecord                          NaN              NaN
oct_time                           NaT              NaT
longest_ws                         NaN              NaN
last_ufc_fight                     NaN              NaN
last_5                 [W, W, W, W, W]  [W, W, W, W, W]
association     Ground Control Academy       Team Ryano
pro_d_date                  2015-10-24       2022-06-25